### ISSUE TITLE
please help to solve it

### ISSUE THREAD

**Issue by ckc** [michaelliao/itranswarp.js#12]
I tried to run `node schema > init_db.sql;` but no any respond awaiting long time.
I also tried run without >, it seems work which asked me create account. Its seems not write successfully. 

06:46:05.924 [Warp@b81f2e1c] CONNECTION: opened from pool: 1
06:46:05.926 [Warp@b81f2e1c] SQL: select `id`, `name`, `tag`, `description`, `display_order`, `created_at`, `updated_at`, `version` from `categories`  order by display_order
06:46:05.929 [Warp@b81f2e1c] CONNECTION: released to pool: 0
X-Execution-Time: 207
[Error] error when handle url: /
Error: ER_NO_SUCH_TABLE: Table 'jack.categories' doesn't exist
    at Query.Sequence._packetToError (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
    at Query.ErrorPacket (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
    at Protocol._parsePacket (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/Connection.js:92:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TCP.onread (net.js:551:20)
    --------------------
    at Protocol._enqueue (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/Protocol.js:135:48)
    at PoolConnection.Connection.query (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/Connection.js:197:25)
    at executeSQL (/root/jack/www/node_modules/mysql-warp/warp.js:46:22)
    at /root/jack/www/node_modules/mysql-warp/warp.js:66:9
    at Handshake.onConnect [as _callback](/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/Pool.js:59:7)
    at Handshake.Sequence.end (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Handshake.Sequence.OkPacket (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/sequences/Sequence.js:105:8)
    at Protocol._parsePacket (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/Protocol.js:39:16)
2016-10-26T22:46:05.930Z [ERROR] 500  Error: ER_NO_SUCH_TABLE: Table 'jack.categories' doesn't exist
    at Query.Sequence._packetToError (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
    at Query.ErrorPacket (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
    at Protocol._parsePacket (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/Connection.js:92:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TCP.onread (net.js:551:20)
    --------------------
    at Protocol._enqueue (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/Protocol.js:135:48)
    at PoolConnection.Connection.query (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/Connection.js:197:25)
    at executeSQL (/root/jack/www/node_modules/mysql-warp/warp.js:46:22)
    at /root/jack/www/node_modules/mysql-warp/warp.js:66:9
    at Handshake.onConnect [as _callback](/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/Pool.js:59:7)
    at Handshake.Sequence.end (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Handshake.Sequence.OkPacket (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/sequences/Sequence.js:105:8)
    at Protocol._parsePacket (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/Protocol.js:39:16)

> > > static path: /favicon.ico
> > > [2016-10-26T22:46:07.354Z] GET /
> > > [Cache] NOT hit: INDEX-MODEL
> > > yield generator to fill cache...
> > > 06:46:07.358 [Warp@b81f2e1c] CONNECTION: opened from pool: 1
> > > 06:46:07.359 [Warp@b81f2e1c] SQL: select `id`, `name`, `tag`, `description`, `display_order`, `created_at`, `updated_at`, `version` from `categories`  order by display_order
> > > 06:46:07.363 [Warp@b81f2e1c] CONNECTION: released to pool: 0
> > > X-Execution-Time: 9
> > > [Error] error when handle url: /
> > > Error: ER_NO_SUCH_TABLE: Table 'jack.categories' doesn't exist
> > >     at Query.Sequence._packetToError (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
> > >     at Query.ErrorPacket (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
> > >     at Protocol._parsePacket (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/Protocol.js:271:23)
> > >     at Parser.write (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/Parser.js:77:12)
> > >     at Protocol.write (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/Protocol.js:39:16)
> > >     at Socket.<anonymous> (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/Connection.js:92:28)
> > >     at emitOne (events.js:96:13)
> > >     at Socket.emit (events.js:188:7)
> > >     at readableAddChunk (_stream_readable.js:176:18)
> > >     at TCP.onread (net.js:551:20)
> > >     --------------------
> > >     at Protocol._enqueue (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/Protocol.js:135:48)
> > >     at PoolConnection.Connection.query (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/Connection.js:197:25)
> > >     at executeSQL (/root/jack/www/node_modules/mysql-warp/warp.js:46:22)
> > >     at /root/jack/www/node_modules/mysql-warp/warp.js:66:9
> > >     at Ping.onPing [as _callback](/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/Pool.js:94:5)
> > >     at Ping.Sequence.end (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
> > >     at Ping.Sequence.OkPacket (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/sequences/Sequence.js:105:8)
> > >     at Protocol._parsePacket (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/Protocol.js:271:23)
> > >     at Parser.write (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/Parser.js:77:12)
> > >     at Protocol.write (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/Protocol.js:39:16)
> > > 2016-10-26T22:46:07.363Z [ERROR] 500  Error: ER_NO_SUCH_TABLE: Table 'jack.categories' doesn't exist
> > >     at Query.Sequence._packetToError (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
> > >     at Query.ErrorPacket (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
> > >     at Protocol._parsePacket (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/Protocol.js:271:23)
> > >     at Parser.write (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/Parser.js:77:12)
> > >     at Protocol.write (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/Protocol.js:39:16)
> > >     at Socket.<anonymous> (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/Connection.js:92:28)
> > >     at emitOne (events.js:96:13)
> > >     at Socket.emit (events.js:188:7)
> > >     at readableAddChunk (_stream_readable.js:176:18)
> > >     at TCP.onread (net.js:551:20)
> > >     --------------------
> > >     at Protocol._enqueue (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/Protocol.js:135:48)
> > >     at PoolConnection.Connection.query (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/Connection.js:197:25)
> > >     at executeSQL (/root/jack/www/node_modules/mysql-warp/warp.js:46:22)
> > >     at /root/jack/www/node_modules/mysql-warp/warp.js:66:9
> > >     at Ping.onPing [as _callback](/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/Pool.js:94:5)
> > >     at Ping.Sequence.end (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
> > >     at Ping.Sequence.OkPacket (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/sequences/Sequence.js:105:8)
> > >     at Protocol._parsePacket (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/Protocol.js:271:23)
> > >     at Parser.write (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/Parser.js:77:12)
> > >     at Protocol.write (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/Protocol.js:39:16)
> > > static path: /favicon.ico
> > > [2016-10-26T22:46:39.856Z] GET /
> > > [Cache] NOT hit: INDEX-MODEL
> > > yield generator to fill cache...
> > > 06:46:39.859 [Warp@b81f2e1c] CONNECTION: opened from pool: 1
> > > 06:46:39.859 [Warp@b81f2e1c] SQL: select `id`, `name`, `tag`, `description`, `display_order`, `created_at`, `updated_at`, `version` from `categories`  order by display_order
> > > 06:46:39.860 [Warp@b81f2e1c] CONNECTION: released to pool: 0
> > > X-Execution-Time: 5
> > > [Error] error when handle url: /
> > > Error: ER_NO_SUCH_TABLE: Table 'jack.categories' doesn't exist
> > >     at Query.Sequence._packetToError (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
> > >     at Query.ErrorPacket (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
> > >     at Protocol._parsePacket (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/Protocol.js:271:23)
> > >     at Parser.write (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/Parser.js:77:12)
> > >     at Protocol.write (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/Protocol.js:39:16)
> > >     at Socket.<anonymous> (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/Connection.js:92:28)
> > >     at emitOne (events.js:96:13)
> > >     at Socket.emit (events.js:188:7)
> > >     at readableAddChunk (_stream_readable.js:176:18)
> > >     at TCP.onread (net.js:551:20)
> > >     --------------------
> > >     at Protocol._enqueue (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/Protocol.js:135:48)
> > >     at PoolConnection.Connection.query (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/Connection.js:197:25)
> > >     at executeSQL (/root/jack/www/node_modules/mysql-warp/warp.js:46:22)
> > >     at /root/jack/www/node_modules/mysql-warp/warp.js:66:9
> > >     at Ping.onPing [as _callback](/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/Pool.js:94:5)
> > >     at Ping.Sequence.end (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
> > >     at Ping.Sequence.OkPacket (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/sequences/Sequence.js:105:8)
> > >     at Protocol._parsePacket (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/Protocol.js:271:23)
> > >     at Parser.write (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/Parser.js:77:12)
> > >     at Protocol.write (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/Protocol.js:39:16)
> > > 2016-10-26T22:46:39.861Z [ERROR] 500  Error: ER_NO_SUCH_TABLE: Table 'jack.categories' doesn't exist
> > >     at Query.Sequence._packetToError (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
> > >     at Query.ErrorPacket (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
> > >     at Protocol._parsePacket (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/Protocol.js:271:23)
> > >     at Parser.write (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/Parser.js:77:12)
> > >     at Protocol.write (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/Protocol.js:39:16)
> > >     at Socket.<anonymous> (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/Connection.js:92:28)
> > >     at emitOne (events.js:96:13)
> > >     at Socket.emit (events.js:188:7)
> > >     at readableAddChunk (_stream_readable.js:176:18)
> > >     at TCP.onread (net.js:551:20)
> > >     --------------------
> > >     at Protocol._enqueue (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/Protocol.js:135:48)
> > >     at PoolConnection.Connection.query (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/Connection.js:197:25)
> > >     at executeSQL (/root/jack/www/node_modules/mysql-warp/warp.js:46:22)
> > >     at /root/jack/www/node_modules/mysql-warp/warp.js:66:9
> > >     at Ping.onPing [as _callback](/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/Pool.js:94:5)
> > >     at Ping.Sequence.end (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
> > >     at Ping.Sequence.OkPacket (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/sequences/Sequence.js:105:8)
> > >     at Protocol._parsePacket (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/Protocol.js:271:23)
> > >     at Parser.write (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/Parser.js:77:12)
> > >     at Protocol.write (/root/jack/www/node_modules/mysql-warp/node_modules/mysql/lib/protocol/Protocol.js:39:16)
> > > static path: /favicon.ico

This is the log. please help to solve. Thx

**Comment by ykfq** [comment]
click "Enter" three times and you'll get a file called "init_db.sql" in folder www.
