### ISSUE TITLE
SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by ckc** [michaelliao/itranswarp.js#21]
[root@cdn-jp www]# node —harmony app.js
/home/itranswarp.js/www/node_modules/koa-bodyparser/index.js:69
  return async function bodyParser(ctx, next) {
               ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/itranswarp.js/www/app.js:12:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

@michaelliao

**Comment by ycc2016** [comment]
同样的问题，请问廖大神如何解决啊？试了好几套环境，没有一套能成功；

**Comment by ckc** [comment]
也是試了幾個nodejs版本 唯有等2.0釋出了，看有更新2.0支綫

**Comment by michaelliao** [comment]
node >= 7.6
