### ISSUE TITLE
启动项目是出现  return binding.readdir(pathModule.toNamespacedPath(path), options.encoding);

### ISSUE THREAD

**Issue by helloMJW** [michaelliao/itranswarp.js#41]
```
s.js:924
  return binding.readdir(pathModule.toNamespacedPath(path), options.encoding);
                 ^
Error: ENOENT: no such file or directory, scandir './views/i18n'
    at Object.fs.readdirSync (fs.js:924:18)
    at Object.loadI18NTranslators (/home/www-data/itranswarp.js/www/i18n.js:34:24)
    at Object.<anonymous> (/home/www-data/itranswarp.js/www/app.js:29:28)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/www-data/itranswarp.js/www/start.js:10:11)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)

```

**Comment by helloMJW** [comment]
问题原因: 没有进入www目录下启动 ```node ./itranswarp.js/www/start.js``` 
解决:
```
cd itranswarp.js/www
node start.js
```
