### ISSUE TITLE
marked baseUrls is not defined

### ISSUE THREAD

**Issue by ckc** [michaelliao/itranswarp.js#46]
ReferenceError: baseUrls is not defined
    at /srv/kbckc/www/node_modules/marked/lib/marked.js:1147:10
    at Object.<anonymous> (/srv/kbckc/www/node_modules/marked/lib/marked.js:1313:4)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/srv/kbckc/www/md.js:10:14)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)

**Comment by zqfmaster** [comment]
marked": "0.3.9" 改为 "marked": "0.3.6" 就可以了。

**Comment by kl2422** [comment]
解决了吗？我改了0.3.6还是不行
